### ISSUE TITLE
python compatibility

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/fetchcommandwrapper#1]
please specify python version (won't run with python3)

**Comment by hartwork** [comment]
Hi!

Are you referring to `#!/usr/bin/env python`?

**Comment by Alessandro-Barbieri** [comment]
No, in the readme.
I found later that is available as ebuild and so first I tried to install manually.

**Comment by hartwork** [comment]
Could you check if Git `HEAD` works with Python 3 for you now?

**Comment by Alessandro-Barbieri** [comment]
Ok, no errors

**Comment by hartwork** [comment]
Excellent, let me push it to PyPI and Gentoo. Thanks for report and testing!

**Comment by hartwork** [comment]
https://github.com/gentoo/gentoo/commit/b7837887d83454752f61416b9487cd33027374a3
