### ISSUE TITLE
enhancement aria2c option variable

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/fetchcommandwrapper#2]
I propose a variable for passing to aria2c extra flags

**Comment by hartwork** [comment]
Does it have to be a variable or would appending to the commend line work as well? To be concrete:
```
fetchcommandwrapper [OPTIONS] URI DISTDIR FILE -- [ARIA2C_OPTION ...]
```
Is this related to https://bugs.gentoo.org/show_bug.cgi?id=617684?

**Comment by Alessandro-Barbieri** [comment]
I confirm that appending `-- --flag` nor `--flag` in `/usr/share/fetchcommandwrapper/make.conf` works
A variable or something customizable from `make.conf` would be great

**Comment by hartwork** [comment]
I have implemented that feature now. Please give it a try and report back.
